# Generated by Django 2.1.1 on 2018-09-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
    ]
